/* eslint-disable */
/**
 * This type was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema.
 */

import { RouteOptions } from './types';

export interface ApiPuzzlesQuerystring {
  id?: string;
}
export interface ApiPuzzlesBody {
  [k: string]: any;
}
export interface ApiPuzzlesHeaders {
  [k: string]: any;
}
export interface ApiPuzzlesParams {
  [k: string]: any;
}
export interface ApiPuzzlesResponse {
  user: {
    _id?: string;
    username?: string;
    solutions: {
      [k: string]: string;
    };
  };
  puzzles: {
    index: number;
    name: string;
    source: string;
  }[];
}
export type ApiPuzzlesRouteOptions = RouteOptions<ApiPuzzlesQuerystring, ApiPuzzlesParams, ApiPuzzlesHeaders, ApiPuzzlesBody>;
export interface ApiSubmitBody {
  id?: string;
  name: string;
  solution: string;
}
export interface ApiSubmitQuerystring {
  [k: string]: any;
}
export interface ApiSubmitHeaders {
  [k: string]: any;
}
export interface ApiSubmitParams {
  [k: string]: any;
}
export interface ApiSubmitResponse {
  user: {
    _id?: string;
    username?: string;
    solutions: {
      [k: string]: string;
    };
  };
}
export type ApiSubmitRouteOptions = RouteOptions<ApiSubmitQuerystring, ApiSubmitParams, ApiSubmitHeaders, ApiSubmitBody>;
export interface LeaderboardEntry {
  username: string;
  length: number;
  date: string;
}
export interface Leaderboard {
  name: string;
  scores: {
    username: string;
    length: number;
    date: string;
  }[];
}
export interface Puzzle {
  index: number;
  name: string;
  source: string;
}
export interface User {
  _id?: string;
  username?: string;
  solutions: {
    [k: string]: string;
  };
}
